### ISSUE TITLE
Use configuration file in home directory

### ISSUE THREAD

**Issue by nirfse** [jacquerie/flask-shell-ptpython#7]
Please make _flask-shell-ptpython_ apply [configurations](https://github.com/jonathanslenders/ptpython/blob/master/examples/ptpython_config/config.py) from `~/.ptpython/config.py` in user's home directory.

**Comment by spookey** [comment]
I just tried the changes from #15 and I can confirm that it works.
If it is not sure which merge request to accept, please don't pick #9 - it uses some hard coded path for the configuration file and therefore won't work on macOS (ptpython configuration is somewhere below ``~/Library/Application Support/..``)

Please merge this very soon, I have a very fine tuned ptpython configuration and would like to use it in a flask shell as well.

**Comment by mgd722** [comment]
@jacquerie I think a lot of us find this very useful! If you could merge #15 and get it on pip that'd be great-- let us know if you need help!

**Comment by mgd722** [comment]
for anyone else who is as impatient as i am, this command will install PR #15 directly:

`pip install --no-cache-dir git+https://github.com/maxnordlund/flask-shell-ptpython.git@patch-1`

you might be able to leave the `--no-cache-dir` if you don't mess it up like 7 times before getting it right like i did.

NOTE: this doesn't seem to work with pip==21.3, but i can confirm it's working on pip==20.2.3.

**Comment by junnplus** [comment]
@nirfse @mgd722 
flask-shell always supported user custom config, we can use 
`pip install flask-shell[ptpython]` to instead of flask-shell-ptpython, PR welcome.

**Comment by nirfse** [comment]
Hey, closing this issue as irrelevant after many years. Feel free to reopen if necessary.
